# Generated by Django 2.0.5 on 2019-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting_request_talent', '0005_auto_20181221_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingrequesttalent',
            name='balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='castingrequesttalent',
            name='commission',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='castingrequesttalent',
            name='gross_wage',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='castingrequesttalent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='castingrequesttalent',
            name='performance_wage',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='castingrequesttalent',
            name='rehearsal_wage',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
