# Generated by Django 2.0.5 on 2019-04-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('talent', '0005_auto_20190219_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentMedicalUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('preview_path', models.CharField(blank=True, max_length=120, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_talent_medical_uploads', to='client.Client')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_talent_medical_uploads', to='talent.Talent')),
            ],
            options={
                'db_table': 'talent_medical_upload',
                'ordering': ('client', 'talent', 'updated', 'name'),
                'managed': True,
            },
        ),
    ]
