# Generated by Django 2.0.5 on 2019-04-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_medical_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentmedicalupload',
            options={'managed': True, 'ordering': ('talent', 'updated', 'name')},
        ),
        migrations.RemoveField(
            model_name='talentmedicalupload',
            name='client',
        ),
    ]
