# Generated by Django 2.0.5 on 2019-04-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casting_request_talent', '0006_auto_20190412_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_date', models.DateTimeField(auto_now_add=True)),
                ('inv_nbr', models.CharField(default='', max_length=100)),
                ('inv_amt', models.FloatField(blank=True, default=0.0)),
                ('amt_paid', models.FloatField(blank=True, default=0.0)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('casting_request_talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_request_talent_invoices', to='casting_request_talent.CastingRequestTalent')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ('id', 'inv_date', 'inv_nbr', 'date_paid'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('id',)},
        ),
    ]
